-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PropertySuggester/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE wbs_propertypairs (
  row_id BIGSERIAL NOT NULL,
  pid1 INT NOT NULL,
  qid1 INT DEFAULT NULL,
  pid2 INT NOT NULL,
  count INT NOT NULL,
  probability FLOAT NOT NULL,
  context TEXT NOT NULL,
  PRIMARY KEY(row_id)
);

CREATE INDEX propertypairs_pid1_pid2_qid1_context ON wbs_propertypairs (pid1, qid1, pid2, context);
