-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PropertySuggester/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wbs_propertypairs (
  row_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  pid1 INTEGER UNSIGNED NOT NULL, qid1 INTEGER UNSIGNED DEFAULT NULL,
  pid2 INTEGER UNSIGNED NOT NULL, count INTEGER UNSIGNED NOT NULL,
  probability DOUBLE PRECISION NOT NULL,
  context BLOB NOT NULL
);

CREATE INDEX propertypairs_pid1_pid2_qid1_context ON /*_*/wbs_propertypairs (pid1, qid1, pid2, context);
