-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: extensions/PropertySuggester/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/wbs_propertypairs (
  row_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL,
  pid1 INT UNSIGNED NOT NULL,
  qid1 INT UNSIGNED DEFAULT NULL,
  pid2 INT UNSIGNED NOT NULL,
  count INT UNSIGNED NOT NULL,
  probability FLOAT NOT NULL,
  context VARBINARY(32) NOT NULL,
  INDEX propertypairs_pid1_pid2_qid1_context (pid1, qid1, pid2, context),
  PRIMARY KEY(row_id)
) /*$wgDBTableOptions*/;
